### PR TITLE
Fix/donor smoker dc

### LINKED ISSUE #46: Add functionality to 'YES' and 'NO' radio buttons
DonateMilk and DonateMilkForm Components
- [x]  'YES' radio should navigate to thank you component
- [x]  'NO' radio should navigate to sorry component

### PR DESCRIPTION
**Pull request by devonwigle**
Is this a fix or a feature?
- [x] Bug fix
- [ ] Feature
- [ ] Refactor
 
Describe the feature - fix - refactor:

- Fix radio buttons to only allow one option
- Add state for form input fields
- Refactor quotation marks in App.js
- Refactor lllusa title to reflect USA link

How was this tested?
- [x] open index.html
- [ ] localhost
- [ ] terminal

Where should the reviewer start - test:

- open dev tools to view donateMilkForm component
- Fill in inputs
- See state change
- If smoked in last 6 weeks selected, on submit should see sorry message
- If have not smoked in last 6 weeks selected, on submit should see a thank you message

Additional comments:
 resolves #46

### CODE REVIEW

File: src/Components/DonateMilkForm/DonateMilkForm.js [hunk 1]
```diff
@@ -1,38 +1,76 @@
 import './DonateMilkForm.scss';
-import { Link } from 'react-router-dom';
+import React, {useState} from 'react';
```
Comment (cagallo) [inline src/Components/DonateMilkForm/DonateMilkForm.js:2]: Great job on this component!

File: src/Components/HomePage/HomePage.js [hunk 2]
```diff
@@ -11,7 +11,7 @@ const HomePage = () => {
            We are here to help families who are not able to nurse their babies or produce enough milk by connecting them with mothers who produce more milk than their babies need. 
            Together, we will help infants thrive by making donated breastmilk accessible.</p>
         <p>The period of time after a baby is born is naturally a very stressful time. Emotions and pressure are high. We understand that breastfeeding issues can be a major contributor to a mother's stress level.
-           We are here for you and you are not alone. Please visit our <Link exact to='/support'>Support Page</Link> to view more resources.</p>
+           We are here for you and you are not alone. Please visit our <Link to='/support'>Support Page</Link> to view more resources.</p>
```
Comment (cagallo) [inline src/Components/HomePage/HomePage.js:14]: Thanks for taking this out!

**Review by cagallo — APPROVED** [review]
Looking great Devon!
